theme: jekyll-theme-cayman
title: Spanish the basics
description: Become bilingual in English and Spanish
github:
  page2: Vocabulary.html
  page3: Gender.html
  page4: Grammar.html
  page5: Morphology.html
  page5: Phonology.html
  
